### ISSUE TITLE
Original or Memorex?

### ISSUE THREAD

**Issue by gearsincorg** [OpenFTC/OpenFTC-app-turbo#3]
I guess I don't understand whether this is: 1) an open-source version of the Full FTC SDK, or 2) a personalized (non standard) version of the FTC SDK.

1) If it's a full version, then it should contain all the components (and not leave out things that new teams may want, like Blocks and OnBot Java).  

On the other hand

2) If it's a Custom Version, then the Readme & Revision info should indicate such.  That is: the readme should not contain references to a WiKi which clearly indicates that there are 3 programming modes, and it should clearly indicate that it's a curated version which may or may not be the same as the "official" version.

Either way, I don't think it's appropriate to have contributing guidlines to this repo that makes references to FIRST or the FTC Tech Team.  Take ownership and create your own guidelines and Wiki.

Phil: A proud "bloatware" contributor.

**Comment by ItsHarper** [comment]
Hi Phil. I'm very sorry for the lack of clear communication here on GitHub about OpenFTC. My original plan was to have this remain quiet until the documentation was ready. In the meantime, I'd only show it to a few people who had expressed interest in either faster deploy times or improving the SDK. Unfortunately, it got leaked (by someone who didn't know it was supposed to be quiet) to an unofficial FTC Discord server, and I only called attention to it by doing my best to clarify the project there. 

Ultimately, I would love to have good communication with the official tech team, so I deeply regret how the bungled launch set things off on the wrong foot with both you and @lizlooney.

What you've said deserves a full, well thought out response that I'm too exhausted to provide right now. Until I get that written, see the top of the readme file again. A couple of hours ago, @WardBenjamin submitted and I accepted a pull request that adds a bit to the top of the README file explaining what the point of OpenFTC is. He did a good job of articulating a lot of my goals for the project. 

In addition, note that there is a version of OpenFTC's app that includes Blocks and OnBotJava: https://github.com/OpenFTC/OpenFTC-app. See my response to Liz ( #4 ) for what I meant by "bloat" and my apology for using that term.

**Comment by gearsincorg** [comment]
Thanks for the considered response.  

You have done the easy part of this project, now the challenge will be to convince FIRST and the community that it's benefits outweigh the possible pitfalls.  This will largely depend on how well you consider it's disposition in relation to the overall competition.

As a coder, I appreciate the ability to access source code  to understand more about the inner workings of any project.  But the impact of this project doesn't stop there.  There are a large number of FTC volunteers, like FTA's, CSA's, and Inspectors, who rely on knowing what's tested and untested to do their jobs, and they need to have full faith in their established support path to go for answers.

As a coder, you can afford to simply consider the benefits of "open source", but as part of the FTC community, you need to cast your viewpoint wider and also consider how your project will ultimately manifest itself on the competition field.   Just publishing the code (as a ready-to-use development environment) without considering the necessity to be able to tell the official version from a derived version was somewhat naive.  

My personal opinion (which in no way effects the GDC: who sets policy) is that being able to make changes to the Robot Controller app is relatively benign (competition wise), with the caveat that there needs to be a definite way for the FTC Competition Staff to absolutely know if a team's App was built from the Official FTC SDK core or not.  Without this irrefutable knowledge, the ability to troubleshoot a team's technical problems at an event is impossible, and I can't imagine anyone wanting to volunteer for this task.  

Anyone choosing to use a modified core should be willing and able to hold up a flag that says "If it doesn't work, it's on us!".

Without this ability, I would vote to outlaw apps derived from non-official SDKs at any event.

You have power here.  I suggest you wield it wisely.

Phil.
All these opinions are my own :)

**Comment by WardBenjamin** [comment]
While it doesn't completely solve the problem, because teams can technically remove it, I've added an indication that the device is running the OpenFTC SDK to several places (The main RC Activity, the Inspection dialog, and through RobotLog). Even if a FTA can't say "this is definitely official", they can say "this is definitely unofficial" if a team runs into problems.

To this end, we might want to add some kind of extra dialog in the main menu that has information about OpenFTC for FTAs who are unfamiliar with it.

**Comment by ftctechnh** [comment]
Hi Folks

I applaud your initiative and resourcefulness, but, I am concerned that a novice user might happen upon this repo and assume that this is an official, _FIRST_-endorsed project.  If a team encounters problems with their build, there might be some confusion about which software is being used and this could make it more difficult for FTAs/CSAs/mentors to support the teams.

I think having the disclaimers or slightly different text still might not prevent a user from getting confused over which version (the "official" or the "open" version) he/she is using.   I think if someone downloads the "open" repo and uses it to build their app, they might assume it's official _FIRST_ because it looks and operates like the official FTC app.  

At a minimum, I recommend that you consider changing the icon used to represent the app generated by the open sdk.  A team might get confused if they see the official FTC logo on their Android device and assume it is an official release of the software.  Also, the trademarked/copyrighted _FIRST_ material are subject to limits on their use and I'm not sure if this instance complies with _FIRST_'s official policy.

**Comment by ftctechnh** [comment]
Also, related to my previous post, if you could change the look of the RC UI so that users know that they used the open version of the sdk to generate their app, that might help.  Again, my primary concern is that a user might unknowingly think they are using the official _FIRST_ software or that an FTA might think they are debugging an official _FIRST_ app.

Perhaps putting some disclaimer/text at the top of the activity indicating that this is your own branded app would help avoid some confusion, especially among FTAs.

**Comment by ItsHarper** [comment]
Hi @ftctechnh, thank you for your feedback. (@gearsincorg as well).

Clearly, we have a lot of work ahead of us (not that I didn't know that before), and I'll keep this issue open until this project is in a state that I (and hopefully the both of you) are comfortable with being actively promoted. We'll improve the clarity of everything as quickly as we can. The main RC screen is one thing that has been improved based on the feedback we've gotten here. It hasn't been merged into this turbo repository just yet, but this is the current version (please disregard the illegal device name). Do you feel it is clear enough, or should we find a way to explicitly say "unofficial" somehow?

![screenshot_2017-10-31-18-45-58](https://user-images.githubusercontent.com/10224994/32252608-82338a4c-be6c-11e7-984f-336bf32b15d2.png)

**Comment by WardBenjamin** [comment]
Additionally, we've added a disclaimer to the Self Inspect screen (also hasn't been merged into Turbo):

![screenshot_20171031-190219](https://user-images.githubusercontent.com/4739008/32252870-2d674d30-be6e-11e7-819f-f77170fb664f.png)

Again, please ignore the illegal device. It's what I had handy to take a screenshot.

I'm also working on actually adding more information to the About screen; is there anything specific you would like to see added?

**Comment by ftctechnh** [comment]
Folks - please do not take my suggestions as an official endorsement of the open sdk.  i do not have the authority to approve or endorse any effort.  As Philbot pointed out, the Game Design Committee would be the group that would rule on the "legality" of an open or modified SDK.

I am mostly concerned about FTAs and users not realizing that the app was generated with a modified version of the software.  I think the screenshots that you posted provide good warnings to the user that this is a non-standard version of the software.  Also, changing the app icons is definitely recommended.

Again, this is not an endorsement or approval of the use of the open sdk.  This is only my personal feedback on whether or not users/FTAs might get confused when troubleshooting the app.

**Comment by ItsHarper** [comment]
Absolutely understood. Changing the icon is ~~definitely on our list~~ done.

**Comment by ItsHarper** [comment]
I hate to take advantage of this thread to ask for a favor, but I really would rather be safe than sorry here. Can either of you verify that the first fix for OpModes stopping made it into [this commit](https://github.com/OpenFTC/OpenFTC-app/commit/04a1124f91784ded46a3d38bd55910b4ce3e818f)? (I know the second one is on the DS side). I was able to quickly see where you accomplished nearly every other change, but nothing jumped out at me as fixing this issue. I want to be certain I didn't miss anything, especially not something this important, and especially since this is the first official update that's been released since we started. Thanks.
