### ISSUE TITLE
v3.5 currently not supported

### ISSUE THREAD

**Issue by Makiah** [OpenFTC/OpenFTC-app-turbo#8]
Not sure whether this is currently in development, but the fact that 3.5 is not supported (and the fixes it provides) makes it more difficult to justify switching from ftc_app.

**Comment by ItsHarper** [comment]
Yeah, this project would be pretty useless if I wasn't committed to updating it. If you look at the OpenFTC/OpenFTC-app repository, you'll see a note in the readme about it. I expect to have both OpenFTC variants updated by the end of the weekend, or possibly Monday at the latest. I'll post here when that happens so you'll get notified. 

I have set things up as best as I can for quick and easy updates, and in the future I'll have a 5-day update promise posted in the README.

**Comment by Makiah** [comment]
Perfect!  I completely understand being too busy to update the entire repository in a single day.

**Comment by ItsHarper** [comment]
The process is actually well on its way. You can see the progress made [here](https://github.com/OpenFTC/OpenFTC-app/commits/unmodified). I could probably have the rest done in 30 minutes if I skipped pulling the latest changes in the main repo to turbo, but since this is the first official update since I started the project, I want to be extra careful to make sure that the process I have in place is thorough. There's also some cleanup work I want to do before merging in 3.5.

**Comment by ItsHarper** [comment]
I didn't get to it quite as soon as I wanted to, but the update is in place.
